### ISSUE TITLE
Cursor in the wrong position when selecting lines with Headings

### ISSUE THREAD

**Issue by SwamiVT** [owenvachell/Obsidian-Graphite-Coast#4]
Hello there,

Whenever selecting a line which is a heading the cursor is not at the end of the lines but rather in the middle of the words visually but when typing will work as normal.

![Screenshot 2021-08-30 233209](https://user-images.githubusercontent.com/53348268/131384434-21a76269-894b-481d-ac21-e2b3a0282476.png)

**Comment by owenvachell** [comment]
I've looked into this previously as I also found it frustrating. It's an unfortunate side-effect of the WYSIWYM implementation using CSS. There's nothing I can do about it. The only option is to carry on as is, or delete the WYSIWYM block from the CSS, which is the bit that looks like this:

```css
/* -------------------
WYSIWYM style editor
Credit: Piotr, Obsidian forum
--------------------- */

div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-header,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-strong,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-em,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-code-block,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-highlight,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-code,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-string.cm-url,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-formatting-link,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-hmd-barelink,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-comment,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-hmd-barelink,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-comment,
div:not(.CodeMirror-activeline)>.CodeMirror-line span.cm-tag {
    display: none;
}
```
